name: Compile Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: Run a multi-line script
      run: |
         echo Add other actions to build,
         echo test, and deploy your project.

    - name: Remove CMake cache files and Makefile
      run: |
             rm -rf CMakeCache.txt cmake_install.cmake Makefile CMakeFiles/

    - name: Build project
      run: |
             cmake -G "Unix Makefiles" -DPROD=OFF -DDEBUG=OFF
    
