name: Test

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Contains a single job called "build"
  build:
    runs-on: windows-latest
    steps:
     - name: performs Integration Tests
         
       id: run_integration_tests
       shell: bash
    
       run: 
              echo"**********************Integration Test is executed!**********************"
              echo "::set-env name=pathToTestFile::${{env.root_dir}}/scripts/integration_tests/"
  
              python run_test.py

              echo::"set-env name=pathToIntTestResult::${{env.root_dir}}/reports/integration_tests/"
          
              mkdir -p ${{env.pathToIntTestResult}} 

              echo::"set-env name=xmlFile::${{env.root_dir}}/scripts/integration_tests/output.xml/"

              echo::"set-env name=reportHtmlFile::${{env.root_dir}}/scripts/integration_tests/report.html/"

              echo::"set-env name=logHtmlFile::${{env.root_dir}}/scripts/integration_tests/log.html/"
