name: Build Project

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove CMake cache files and Makefile
      run: |
        rm -rf CMakeCache.txt cmake_install.cmake Makefile CMakeFiles/

    - name: Build project
      run: |
        cmake -G "Unix Makefiles" -DPROD=OFF -DDEBUG=OFF .
        make
